-- Venus Enterprises - Sample Data (for reference only)
-- This matches your schema: name (PRIMARY KEY), category, price, stock, image, description

INSERT INTO products (name, category, price, stock, image, description) VALUES
('Premium Wooden Name Plate', 'Wooden', 1299, 50, '/images/wooden/wooden-name-plate.jpg', 'Elegant wooden name plate with laser engraving. Perfect for office desks and executive cabins.'),
('Crystal Excellence Award', 'Crystal', 3499, 25, '/images/crystal/crystal-award.jpg', 'Premium crystal award trophy for recognition ceremonies. Optical crystal with laser engraved text.'),
('Metal Executive Pen', 'Metal', 799, 100, '/images/metal/metal-pen.jpg', 'Stainless steel executive pen with precision laser engraving. Smooth ink flow and premium finish.'),
('Acrylic LED Name Plate', 'Acrylic', 1899, 40, '/images/acrylic/acrylic-name-plate.jpg', 'Modern acrylic name plate with LED backlighting. Touch-sensitive on/off switch.'),
('Corporate Gift Hamper', 'Gifts', 4999, 30, '/images/gifts/corporate-hamper.jpg', 'Luxury corporate gift hamper with premium items. Perfect for client appreciation.'),
('Wooden Plaque of Appreciation', 'Wooden', 1799, 45, '/images/wooden/wooden-plaque.jpg', 'Elegant wooden plaque for appreciation awards. Custom message engraving available.'),
('Metal Business Card Holder', 'Metal', 699, 75, '/images/metal/card-holder.jpg', 'Premium stainless steel business card holder with engraved logo.'),
('Crystal Paperweight', 'Crystal', 999, 60, '/images/crystal/paperweight.jpg', 'Optical crystal paperweight with laser engraved message. Classic executive gift.'),
('Acrylic Trophy Award', 'Acrylic', 1599, 35, '/images/acrylic/trophy.jpg', 'Modern acrylic trophy for corporate competitions. Clear with colored base.'),
('Leather Folio Set', 'Gifts', 2799, 40, '/images/gifts/leather-folio.jpg', 'Premium leather folio with engraved metal plate. Includes notepad and pen slot.'),
('Marble Base Award', 'Marble', 3999, 20, '/images/marble/marble-award.jpg', 'Elegant marble base award with metal plate. Perfect for lifetime achievement.'),
('Wooden Photo Frame', 'Wooden', 899, 80, '/images/wooden/photo-frame.jpg', 'Handcrafted wooden photo frame with engraved message. Ideal for farewell gifts.'),
('Metal Keychain Set', 'Metal', 399, 200, '/images/metal/keychain.jpg', 'Set of 2 stainless steel keychains with laser engraving. Great promotional item.'),
('Acrylic Desk Sign', 'Acrylic', 1199, 55, '/images/acrylic/desk-sign.jpg', 'Elegant acrylic desk sign with custom engraved text. Perfect for reception.'),
('Crystal Star Award', 'Crystal', 2899, 30, '/images/crystal/star-award.jpg', 'Stunning crystal star award for excellence recognition.'),
('Memento of Gratitude', 'Mementos', 1499, 65, '/images/mementos/gratitude-plaque.jpg', 'Beautiful memento to express gratitude and appreciation.'),
('Marble Paperweight', 'Marble', 1299, 40, '/images/marble/paperweight.jpg', 'Elegant marble paperweight with engraved metal plate. Classic desk accessory.'),
('Wooden Award Shield', 'Wooden', 2199, 35, '/images/wooden/shield.jpg', 'Traditional wooden shield award for special recognition.'),
('Metal Desk Clock', 'Metal', 1699, 50, '/images/metal/desk-clock.jpg', 'Elegant metal desk clock with engraved plate. Silent quartz movement.'),
('Gift Voucher Set', 'Gifts', 999, 100, '/images/gifts/voucher.jpg', 'Premium gift voucher set in elegant presentation box.'),
('Acrylic Plaque', 'Acrylic', 1399, 45, '/images/acrylic/plaque.jpg', 'Clear acrylic plaque with engraved text. Modern design for any office.'),
('Crystal Globe Award', 'Crystal', 4499, 15, '/images/crystal/globe.jpg', 'Elegant crystal globe award for international achievements.'),
('Wooden Pen Stand', 'Wooden', 599, 90, '/images/wooden/pen-stand.jpg', 'Handcrafted wooden pen stand with engraved base. Holds multiple pens.'),
('Metal Money Clip', 'Metal', 449, 150, '/images/metal/money-clip.jpg', 'Slim stainless steel money clip with laser engraving. Practical gift.'),
('Memento of Service', 'Mementos', 1899, 40, '/images/mementos/service-award.jpg', 'Elegant memento for years of service recognition.'),
('Marble Plaque', 'Marble', 3299, 25, '/images/marble/plaque.jpg', 'Premium marble plaque with metal inscription. Perfect for corporate awards.'),
('Corporate Diary Set', 'Gifts', 1499, 60, '/images/gifts/diary-set.jpg', 'Premium leather diary set with pen. Custom embossing available.'),
('Acrylic Award', 'Acrylic', 999, 70, '/images/acrylic/award.jpg', 'Modern acrylic award for various recognition needs.'),
('Wooden Troph', 'Wooden', 1599, 45, '/images/wooden/trophy.jpg', 'Elegant wooden trophy for sports and corporate events.'),
('Metal Pen & Keychain Set', 'Metal', 999, 80, '/images/metal/pen-keychain-set.jpg', 'Premium metal pen and keychain set in gift box.');